version: '3.7'
services:
  # App backend service
  app-server:
    container_name: backend-spring
    build:
      context: aspice-reporting
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/aspice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - backend
      - frontend

  # Frontend Service 
  app-client:
    container_name: frontend-react
    build:
      context: aspice-reporting-react
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  

  # Database Service
  db:
    container_name: pogtgres-db
    image: postgres:14.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aspice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend  
# Volumes
volumes:
  pgdata:

networks:
  backend:
  frontend: 