version: '3'
services:
  postgresdb:
    image: postgres:14.2
    restart: unless-stopped
    container_name: postgres-dev
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_DB: aspice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
